AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Weather Aggregator API

Globals:
  Function:
    Runtime: java17
    MemorySize: 2048
    Timeout: 29

Resources:
  WeatherAggregatorAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  WeatherAggregatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.weather.app.StreamLambdaHandler::handleRequest
      CodeUri: target/serverless-api-0.0.1-SNAPSHOT-lambda-package.zip
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref WeatherAggregatorAPI

Outputs:
  WeatherAggregatorEndpoint:
    Description: Weather Aggregator API Endpoint
    Value:
      Fn::Sub: https://${WeatherAggregatorAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/